---
- name: install & start bind9
  hosts: all
  remote_user: msu
  become: True

  tasks:
  - name: install bind9 bind9utils bind9doc
    apt:
      name: '{{ item }}'
      state: present
    with_items:
    - bind9
    - bind9utils
    - bind9-doc
  - name: start & enable bind9
    service:
      name: bind9
      state: started
      enabled: True
  - name: install vim
    apt:
      name: vim
      state: present
