---
- hosts: all
  user: root
  tasks:
  - name: msu anlegen
    user: 
      name: msu
      state: present
      comment: Michael
  - name: set auth key for msu
    authorized_key:
      user: msu
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: Install sudo on debian
    apt:
      name: sudo
      state: present

  - name: msu ist sudoer
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^msu ALL\='
      line: 'msu ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
