---
- hosts: all
  remote_user: msu
  tasks:
  - name: epel installieren
    yum:
      name: epel-release
      state: present
    become: True
  - name: httpd & firewalld installieren
    yum:
      name: '{{ item }}'
      state: latest
    become: True
    with_items:
    - httpd
    - firewalld
    when: ansible_os_family == 'RedHat'
  - name: httpd & firewalld start & enable
    service:
      name: '{{ item }}'
      state: started
      enabled: True
    become: True
    with_items:
    - httpd
    - firewalld
  - name: http & https pass firewalld
    firewalld:
      service: '{{ item }}'
      state: enabled
      immediate: True
      permanent: True
    become: True
    with_items:
    - http
    - https
  
