---
- name: configure dns client
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
  tags: dns
- name: install ntp
  yum:
    name: ntp
    state: present
  tags: ntp
- name: copy ntp config file
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp service
