---
- name: install apache
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - httpd
  - httpd-tools
- name: copy apache index file
  copy:
    src: index.html.j2
    dest: /var/www/html/index.html
  tags: apache
  notify: restart apache service
