---
- hosts: all
  user: root
  tasks:
  - name: user msu anlegen
    user:
      name: msu
      state: present
      comment: msu
  - name: Set auth key for user msu copying it from current user
    authorized_key:
      user: msu
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: msu wird sudoer
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^msu ALL\='
      line: 'msu ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
