---
- hosts: all
  remote_user: msu
  become: True
 
  tasks:
  - name: create groups
    group:
      name: '{{ item }}'
      state: present
    with_items:
    - group1
    - group2
    - group3
    tags: add_new_group

  - name: add users
    user:
      name: '{{ item }}'
      state: present
      groups: group1
      password: "sun123"
      shell: /bin/bash
    with_items:
    - tina
    - juli
    - leon
    - linus
    - maxi
    tags: add_new_user

  - name: generate ssh keys
    user:
      name: '{{ item }}'
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
    with_items:
    - tina
    tags: generate_ssh_keys

  - name: update authorized keys
    authorized_key: 
      user: tina
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    tags: copy_pub_key

  - name: delete several users
    user:
      name: '{{ item }}'
      state: present
    with_items:
    - leon
    - maxi
    tags: remove_user

  - name: delete several groups
    group:
      name: '{{ item }}'
      state: absent
    with_items:
    - group2
    - group3
